### ISSUE TITLE
some improvements

### ISSUE THREAD

**Issue by ikwattro** [ikwattro/KDBParametersBundle#1]
iaw @Sergic mail, the following improvements will be included: 

clearParam
clearParams
getParam

new config parameter: default-return who will return by default an exception.if the value name does not exist

**Comment by Sergic** [comment]
i think about other...
compromise:
- need critical table column for parameter
  or
- in config some parameter that promote returning default value or exception

default in config is not good.
imagine we have such parameters:
site_name
items_per_page
default_culture

in config we set 
  default-return: sometext
and that we get in the outcome if three are not >2 params? - something not understandable

so

if ($param->getCritical()){
//to do some exception
}
else{
//return $default ('some text value' or null)
}

but i need return this null value and set default param in method ))

**Comment by ikwattro** [comment]
I don't really understant what you want ?

What is the purpose of the critical ?

The default-return config parameter is for my part the better bad solution, for me the better solution is to return an exception if the parameter does not exist (seems more logic).

I'll try to post a P.R. tommorow evening.

**Comment by Sergic** [comment]
sorry if can't explained you.
i want to set default value in getter method. if there is no value - return null.
see founded class http://trac.symfony-project.org/browser/branches/1.4/lib/config/sfConfig.class.php  on symfony 1.4

**Comment by ikwattro** [comment]
Latest commits add getParam method for the bundle with an argument for the return if no value

$kdb = $this->container->get('kparams');
$kdb->findParam('site_name', 'oops');

**Comment by ikwattro** [comment]
@Sergic pls take a look at /cc #2 to see if it fit your needs

**Comment by Sergic** [comment]
ok looks seems not bad

## why not use memory for parameter (save all parameters once in protected array property)

return $this->parameterManager->findParamByName($name);
this string will do mysql query every call of this function

**Comment by ikwattro** [comment]
Can not mind up what you want, maybe if you do a PR I can take a closer look to it.

**Comment by Sergic** [comment]
to use pattern Registry design pattern for save in memory parameters and then use getParam function to get value from array  
don't you think so?
load all parameters at once

```
private $params = null; // will convert to array()
private function getAllParams()
{
    if (!$this->params)
    {
        $allParameters = $this->parameterManager->findParams();
        $params = array();
        foreach ($allParameters as $k=>$v)
        {
            if ($v->getActive() == 1)
            {
                $params[$v->getName()] = $v->getValue();
            }
        }
        $this->params = $params;
    }
    return $this->params;
}
```
